name: rl
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.12.9
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - fonttools==4.57.0
      - gymnasium==1.1.1
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - numpy==1.26.4
      - packaging==25.0
      - pillow==11.2.1
      - protobuf==6.30.2
      - pygame==2.6.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - six==1.17.0
      - tensorboardx==2.6.2.2
      - typing-extensions==4.13.2
#prefix: /Users/kash/miniconda/envs/rl
